version: "3.7"

services:

  tester:
    build:
      context: .
      target: tester

  coverage:
    build:
      context: .
      target: coverage
    volumes:
      - ./htmlcov/:/htmlcov
    ports:
      - 8000:8000
